# Generated by Django 4.1.3 on 2022-11-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_appointment_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='specialization',
        ),
    ]
