# Generated by Django 4.1.3 on 2022-11-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_appointment_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('date', models.DateField(help_text='YYYY-MM-DD')),
                ('timeslot', models.IntegerField(choices=[(0, '09:00 – 09:30'), (1, '10:00 – 10:30'), (2, '11:00 – 11:30'), (3, '12:00 – 12:30'), (4, '13:00 – 13:30'), (5, '14:00 – 14:30'), (6, '15:00 – 15:30'), (7, '16:00 – 16:30'), (8, '17:00 – 17:30')])),
                ('patient_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Pre-appointment',
                'verbose_name_plural': 'Pre-appointments',
                'unique_together': {('doctor_id', 'date', 'timeslot')},
            },
        ),
    ]
